export enum BUSINESS_DOMAIN {
  GROCERY = "GROCERY",
  RESTAURANT = "RESTAURANT",
  ECOMMERCE = "ECOMMERCE",
  CATERY = "CATERY"
}

export enum COMPANY_TYPE {
  FLEET = "FLEET",
  DELIVERY = "DELIVERY"
}

export enum SIGNATURE_TYPE {
  NO_CONTACT = "NO_CONTACT",
  SIGN = "SIGN"
}